---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start Apache
      systemd: 
        name: httpd
        state: started

    - name: Copy index.html
      copy: 
        src: templates/index.html
        dest: /var/www/html/index.html


  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
